### ISSUE TITLE
классы

### ISSUE THREAD

**Issue by iljuhy** [Freeduba/Landing-Page#1]
https://github.com/Freeduba/Landing-Page/blob/fbfd2fe056cad7585d66df153d8e155476fa183f/html/index.html#L12

**Comment by iljuhy** [comment]
Без классов у тегов сложно понять для чего они нужны, не бойся придумывать классы для тегов, легче будит получить к ним доступ в стилях.

**Comment by Freeduba** [comment]
Да заметил! Уже добавил классы! Спасибо!
